log:
  level: debug
  disable_sentry: true

db:
  url: db_url

listener:
  addr: :8000

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: btc-utxo-indexer
  service_port: 80

service:
  access_token_key: "something sha256'd, has to be a 64 char long hex string"
  access_token_expire_time: 1h or other value, see time.ParseDuration
  refresh_token_key: "something sha256'd, has to be a 64 char long hex string"
  refresh_token_expire_time: 8h or other value, see time.ParseDuration
  nodes:
    "electrum.blockstream.info:50002":
      ssl: true
      reconnect_attempts: 5
    "electrum.blockstream.info:50001":
      ssl: false
      reconnect_attempts: 5
    "electrum.cakewallet.com:50002":
      ssl: true
      reconnect_attempts: 5
